github: 'cfillion/reapack'
files:
  'reaper_reapack32.dylib': darwin32
  'reaper_reapack64.dylib': darwin64
  'reaper_reapack32.dll': win32
  'reaper_reapack64.dll': win64
  'reaper_reapack32.so': linux32
  'reaper_reapack64.so': linux64
